export enum CheckoutStatus {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  IN_PROGRESS = "IN_PROGRESS",
  ARRIVED = "ARRIVED",
  DECLINED = "DECLINED",
  RETURNED = "RETURNED",
  FULLFILLED = "FULLFILLED",
}
